name: Integrate
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: holepunchto/actions/node-base@v1
      - run: npm run lint
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: macos
    runs-on: ${{ matrix.os }}
    name: Test / ${{ matrix.platform }}
    steps:
      - uses: holepunchto/actions/bare-base@v1

      - name: Install fixture dependencies
        shell: bash
        run: for dir in test/fixtures/*/; do (cd "$dir" && npm install --install-links); done

      - name: Run tests
        run: ${{ matrix.platform == 'linux' && 'xvfb-run ' || '' }}npm test
